### ISSUE TITLE
Image generation fails when "Show individual ships" is not selected

### ISSUE THREAD

**Issue by drnlm** [Jasperhawk/BSG-Moderator-Tools#28]
With recent versions of OpenOffice and LibreOffice, image generation fails if the "Show individual Ships option" is not selected since the generated CSV file contains a literal 0, rather than a string, for that option.

I fixed it here by changing 'Image Data'.B32 to be
`=IF('Game State'.W29=0,"",'Game State'.W29)` instead of just `'Game State'.W29`

**Comment by mawkee** [comment]
Months later...

I could not reproduce this error on the newest version of the spreadsheet. The "Option" is commented out (with a semicolon) when the field is not used anyway. Can you check the version of the spreadsheet you're using, or send it to me at mawkee@gmail.com?

**Comment by drnlm** [comment]
I'm able to reproduce with the version of the spreadsheet currently available from the repository. 

The option is only commented out if the second field is empty - it doesn't get commented out if the value is 0, which is what's happening here.

This may be a version issue - I'm running a fairly recent LibreOffice insatllation rather than OpenOffice, although when initally reporting the issue I did test on a machine with OpenOffice, but I didn't check how recent an installtion that was.

Spreadsheet and generated CSV file sent

**Comment by mawkee** [comment]
Please check in the newest version (released today)

**Comment by drnlm** [comment]
Released where? github is currently still at e272bb9cb846be8fd414f6c4c5e4aeea5202face from Dec 29, and there doesn't appear to have been an update on BGG that I can find.

Thanks.

**Comment by mawkee** [comment]
It was in the process of syncing. Slow connection

**Comment by drnlm** [comment]
It still fails as before if I create the game and then immediately try create an image.

However, if I toggle the options on and off, it correctly disables things (which didn't happen previously), so it's now easy enough to work around the problem.

**Comment by mawkee** [comment]
I think I found the problem. It seems to be LibreOffice exclusive, that's why I wasn't able to reproduce. Please test with the new version (about to be updated in a few minutes)

**Comment by drnlm** [comment]
That fixes the issue with ships, thanks.

The same fix should be applied to 'Game State'.W27, since the Option in A51 of the Image Data tab behaves the same way (I forgot that I'd also added a workaround there with the older version).
